# Da Greetings

greetings = [
    [ "Afrikaans",      "Goeie môre" ]
    [ "Albanian",       "Mirëmëngjes" ]
    [ "Amharic",        "Endermen aderkh" ]
    [ "Arabic",         "Sabah-il-kheir" ]
    [ "Aramaic",        "Yasetel liesbukh" ]
    [ "Armenian",       "Bari luys" ]
    [ "Assyrian",       "Kedamtookh brikhta" ]
    [ "Azerbaijani",    "Sabahiniz Xeyr" ]
    [ "Bamougoum",      "Oli yah" ]
    [ "Bangla",         "Shuvo sokal" ]
    [ "Basque",         "Egun on" ]
    [ "Belarussian",    "Dobray ranitsy" ]
    [ "Bemba",          "Mwashibukeni" ]
    [ "Bengali",        "Shu-probhaat" ]
    [ "Bisaya",         "Maayong adlaw" ]
    [ "Binary",         "011001110110111101101111011001000010000001101101011011110111001001101110011010010110111001100111" ]
    [ "Bosnian",        "Dobro jutro" ]
    [ "Bulgarian",      "Dobro utro" ]
    [ "Cantonese",      "Zou san" ]
    [ "Catalan",        "Bon dia" ]
    [ "Cebuano",        "Maayong buntag!" ]
    [ "Chichewa",       "Mwadzuka bwanji" ]
    [ "Chinese",        "Zao shang hao" ]
    [ "Mandarin",       "Zao shang hao" ]
    [ "Cornish",        "Myttin da" ]
    [ "Corse",          "Bun ghjiornu" ]
    [ "Creole",         "Bonjou" ]
    [ "Croatian",       "Dobro jutro" ]
    [ "Czech",          "Dobré ráno" ]
    [ "Danish",         "God morgen" ]
    [ "Dari",           "Sob Bakhaer" ]
    [ "Divehi",         "Baajjaveri hedhuneh" ]
    [ "Dutch",          "Goedemorgen" ]
    [ "English",        "Good morning" ]
    [ "Esperanto",      "Bonan matenon" ]
    [ "Estonian",       "Tere hommikust" ]
    [ "Etsakor",        "Naigbia" ]
    [ "Fanti",          "Me ma wo akye" ]
    [ "Fijian",         "Sa Yadra" ]
    [ "Filipino",       "Magandang umaga po" ]
    [ "Finnish",        "Hyvää huomenta" ]
    [ "Flanders",       "Hey-Diddly-Ho" ]
    [ "Flemish",        "Goeie morgen" ]
    [ "French",         "Bonjour" ]
    [ "Frisian",        "Goeie moarn" ]
    [ "Galician",       "Bos dias" ]
    [ "Georgian",       "Dila mshvidobisa" ]
    [ "German",         "Guten Morgen" ]
    [ "Greek",          "Kali mera" ]
    [ "Greenlandic",    "Iterluarit" ]
    [ "Gujarati",       "Subh Prabhat" ]
    [ "Hakka",          "On zoh" ]
    [ "Hausa",          "Inaa kwana" ]
    [ "Hawaiian",       "Aloha kakahiaka" ]
    [ "Hebrew",         "Boker tov" ]
    [ "Hexadecimal",    "67 6F 6F 64 20 6D 6F 72 6E 69 6E 67" ]
    [ "Hiligaynon",     "Maayong aga" ]
    [ "Hindi",          "Shubh prabhat" ]
    [ "Hungarian",      "Jo reggelt" ]
    [ "Icelandic",      "Gódan daginn" ]
    [ "Ilocano",        "Naimbag nga Aldaw" ]
    [ "Indonesian",     "Selamat pagi" ]
    [ "Irish",          "Dia duit ar maidin" ]
    [ "Italian",        "Buon giorno" ]
    [ "Japanese",       "Ohayo gozaimasu" ]
    [ "Kannada",        "Shubhodaya" ]
    [ "Kapampangan",    "Mayap a abak" ]
    [ "Kazakh",         "Kairly Tan" ]
    [ "Khmer",          "Arrun Suo Sdey" ]
    [ "Kimeru",         "Muga rukiiri" ]
    [ "Kinyarwanda",    "Muraho" ]
    [ "Konkani",        "Dev Tuka Boro Dis Divum" ]
    [ "Korean",         "Annyunghaseyo" ]
    [ "Kurdish Badini", "Spede bash" ]
    [ "Kurdish Sorani", "Beyani bash" ]
    [ "Lao",            "Sabaidee" ]
    [ "Latin",          "Bonum mane" ]
    [ "Latvian",        "Labrit" ]
    [ "Lithuanian",     "Labas rytas" ]
    [ "Lozi",           "U zuhile" ]
    [ "Luganda",        "Wasuze otyano" ]
    [ "Luo",            "Oyawore" ]
    [ "Luxembourg",     "Gudde moien" ]
    [ "Macedonian",     "Dobro utro" ]
    [ "Malayalam",      "Suprabhatham" ]
    [ "Malay",          "Selamat pagi" ]
    [ "Maltese",        "Għodwa it-tajba" ]
    [ "Manx",           "Moghrey mie" ]
    [ "Maori",          "Ata marie" ]
    [ "Mapudungun",     "Mari mari" ]
    [ "Marathi",        "Suprabhat" ]
    [ "Mongolian",      "Öglouny mend" ]
    [ "Navajo",         "Yá'át'ééh abíní" ]
    [ "Ndebele",        "Livukenjani" ]
    [ "Nepali",         "Subha prabhat" ]
    [ "Northern Sotho", "Thobela" ]
    [ "Norwegian",      "God morgen" ]
    [ "Owambo",         "Wa lalapo" ]
    [ "Pashto",         "Sahar de pa Khair" ]
    [ "Persian",        "Subbakhair" ]
    [ "Pirate",         "Avast, ye scurvy dog" ]
    [ "Polish",         "Witaj" ]
    [ "Polynesian",     "Ia ora na" ]
    [ "Portuguese",     "Bom dia" ]
    [ "Punjabi",        "Sat Shri Akal" ]
    [ "Rapa Nui",       "Iorana" ]
    [ "Romanian",       "Buna dimineata" ]
    [ "Russian",        "Dobroye utro" ]
    [ "Samoan",         "Talofa lava" ]
    [ "Sanskrit",       "Suprabhataha" ]
    [ "Sardinian",      "Bona dia" ]
    [ "Serbian",        "Dobro jutro" ]
    [ "Shona",          "Mangwanani" ]
    [ "Sinhalese",      "Suba Udesanak Wewa" ]
    [ "Slovak",         "Dobré ráno" ]
    [ "Slovenian",      "Dobro jutro" ]
    [ "Somalian",       "Subax wanaagsan" ]
    [ "Southern Sotho", "Dumela" ]
    [ "Spanish",        "Buenos dias" ]
    [ "Swahili",        "Habari za asubuhi" ]
    [ "Swazi",          "Sawubona" ]
    [ "Swedish",        "God morgon" ]
    [ "Tagalog",        "Magandang umaga" ]
    [ "Taiwanese",      "Gau cha" ]
    [ "Tamil",          "Kaalai Vannakkam" ]
    [ "Telugu",         "Subhodayamu" ]
    [ "Tetum",          "Dader diak" ]
    [ "Thai",           "Aroon-Sawass" ]
    [ "Tibetan",        "Nyado delek" ]
    [ "Tonga",          "Mwabuka buti" ]
    [ "Tswana",         "Dumela" ]
    [ "Twi",            "Me ma wo maakye" ]
    [ "Turkish",        "Günaydin" ]
    [ "Turkmen",        "Ertiringiz haiyirli bolsun" ]
    [ "Ukrainian",      "Dobri ranok" ]
    [ "Urdu",           "Subha Ba-khair" ]
    [ "Uzbek",          "Khairli kun" ]
    [ "Vietnamese",     "Xin chao" ]
    [ "Welsh",          "Bore da" ]
    [ "Xhosa",          "Bhota" ]
    [ "Xitsonga",       "Avuxeni" ]
    [ "Yoruba",         "E karo" ]
    [ "Zulu",           "Sawubona" ]
    [ "!Kung san",      "Tuwa" ]
    [ "Australian",     "G'day" ]
    [ "Klingon",        "nuqneH" ]
    [ "tlhIngan Hol",   "nuqneH" ]
    [ "Vulcan",         "Dif-tor heh smusma" ]
    [ "Romulan",        "Brhon mnekha" ]
    [ "Ferengi",        "Welcome to our home. Please place your thumbprint on the legal waivers and deposit your admission fee in the slot by the door. Remember, my house is my house," ]
    [ "Bajoran",        "Soraya neryshu" ]
    [ "Malkovich",      "Malkovich Malkovich Malkovich," ]
    [ "Frozen",         "Let it go," ]
    [ "Doc",            "Great Scott," ]
    [ "Captain Jack",   "http://33.media.tumblr.com/d27594fa4e9788bd23c98e1617737527/tumblr_n70xx6I4ZA1s9qnu2o2_500.gif" ]
    [ "Pintel",         "Hello Poppet," ]
    [ "Buzz",           "To infinity and beyond," ]
    [ "Thundercats",    "Thundercats Ho," ]
    [ "Anchorman",      "Newsteam assemble," ]
    [ "Wonka",          "Good morning starshine, the earth says hello," ]
    [ "Pink Floyd",     "Hello, is there anybody in there? Just nod if you can hear me. Is there anyone at home?" ]
    [ "Lionel Richie",  "Hello! Is it me you're looking for?" ]
    [ "Beatles",        "Good morning, good morning. Good morning ah" ]
    [ "Megamind",       "Ollo?" ]
    [ "Rickroll",       "Never gonna give you up, Never gonna let you down, Never gonna run around and desert you, Never gonna make you cry, Never gonna say goodbye, Never gonna tell a lie and hurt you." ]
]

class GreetingsRepository
    GREETINGS = []

    constructor: ->
        for greeting in greetings
            [lang, greet] = greeting[0..1]
            GREETINGS[lang.toLowerCase()] = lang: lang, greeting: greet

    find: (name) ->
        GREETINGS[name.toLowerCase()]

    findOrRandom: (robot, name) ->
        name? && @find(name) || @random(robot)

    greeting: (name) ->
        @find(name)?.greeting

    all: ->
        GREETINGS

    names: ->
        for v of GREETINGS
            v.lang

    keys: ->
        Object.keys(GREETINGS)

    random: (robot) ->
        GREETINGS[robot.random @keys()]


module.exports = GreetingsRepository
