# Da Greetings

greetings =
"afrikaans":      lang: "Afrikaans",      greeting: "Goeie môre"
"albanian":       lang: "Albanian",       greeting: "Mirëmëngjes"
"amharic":        lang: "Amharic",        greeting: "Endermen aderkh"
"arabic":         lang: "Arabic",         greeting: "Sabah-il-kheir"
"aramaic":        lang: "Aramaic",        greeting: "Yasetel liesbukh"
"armenian":       lang: "Armenian",       greeting: "Bari luys"
"assyrian":       lang: "Assyrian",       greeting: "Kedamtookh brikhta"
"azerbaijani":    lang: "Azerbaijani",    greeting: "Sabahiniz Xeyr"
"bamougoum":      lang: "Bamougoum",      greeting: "Oli yah"
"bangla":         lang: "Bangla",         greeting: "Shuvo sokal"
"basque":         lang: "Basque",         greeting: "Egun on"
"belarussian":    lang: "Belarussian",    greeting: "Dobray ranitsy"
"bemba":          lang: "Bemba",          greeting: "Mwashibukeni"
"bengali":        lang: "Bengali",        greeting: "Shu-probhaat"
"bisaya":         lang: "Bisaya",         greeting: "Maayong adlaw"
"binary":         lang: "Binary",         greeting: "011001110110111101101111011001000010000001101101011011110111001001101110011010010110111001100111"
"bosnian":        lang: "Bosnian",        greeting: "Dobro jutro"
"bulgarian":      lang: "Bulgarian",      greeting: "Dobro utro"
"cantonese":      lang: "Cantonese",      greeting: "Zou san"
"catalan":        lang: "Catalan",        greeting: "Bon dia"
"cebuano":        lang: "Cebuano",        greeting: "Maayong buntag!"
"chichewa":       lang: "Chichewa",       greeting: "Mwadzuka bwanji"
"chinese":        lang: "Chinese",        greeting: "Zao shang hao"
"mandarin":       lang: "Mandarin",       greeting: "Zao shang hao"
"cornish":        lang: "Cornish",        greeting: "Myttin da"
"corse":          lang: "Corse",          greeting: "Bun ghjiornu"
"creole":         lang: "Creole",         greeting: "Bonjou"
"croatian":       lang: "Croatian",       greeting: "Dobro jutro"
"czech":          lang: "Czech",          greeting: "Dobré ráno"
"danish":         lang: "Danish",         greeting: "God morgen"
"dari":           lang: "Dari",           greeting: "Sob Bakhaer"
"divehi":         lang: "Divehi",         greeting: "Baajjaveri hedhuneh"
"dutch":          lang: "Dutch",          greeting: "Goedemorgen"
"english":        lang: "English",        greeting: "Good morning"
"esperanto":      lang: "Esperanto",      greeting: "Bonan matenon"
"estonian":       lang: "Estonian",       greeting: "Tere hommikust"
"etsakor":        lang: "Etsakor",        greeting: "Naigbia"
"fanti":          lang: "Fanti",          greeting: "Me ma wo akye"
"fijian":         lang: "Fijian",         greeting: "Sa Yadra"
"filipino":       lang: "Filipino",       greeting: "Magandang umaga po"
"finnish":        lang: "Finnish",        greeting: "Hyvää huomenta"
"flanders":       lang: "Flanders",       greeting: "Hey-Diddly-Ho"
"flemish":        lang: "Flemish",        greeting: "Goeie morgen"
"french":         lang: "French",         greeting: "Bonjour"
"frisian":        lang: "Frisian",        greeting: "Goeie moarn"
"galician":       lang: "Galician",       greeting: "Bos dias"
"georgian":       lang: "Georgian",       greeting: "Dila mshvidobisa"
"german":         lang: "German",         greeting: "Guten Morgen"
"greek":          lang: "Greek",          greeting: "Kali mera"
"greenlandic":    lang: "Greenlandic",    greeting: "Iterluarit"
"gujarati":       lang: "Gujarati",       greeting: "Subh Prabhat"
"hakka":          lang: "Hakka",          greeting: "On zoh"
"hausa":          lang: "Hausa",          greeting: "Inaa kwana"
"hawaiian":       lang: "Hawaiian",       greeting: "Aloha kakahiaka"
"hebrew":         lang: "Hebrew",         greeting: "Boker tov"
"hexadecimal":    lang: "Hexadecimal",    greeting: "67 6F 6F 64 20 6D 6F 72 6E 69 6E 67"
"hiligaynon":     lang: "Hiligaynon",     greeting: "Maayong aga"
"hindi":          lang: "Hindi",          greeting: "Shubh prabhat"
"hungarian":      lang: "Hungarian",      greeting: "Jo reggelt"
"icelandic":      lang: "Icelandic",      greeting: "Gódan daginn"
"ilocano":        lang: "Ilocano",        greeting: "Naimbag nga Aldaw"
"indonesian":     lang: "Indonesian",     greeting: "Selamat pagi"
"irish":          lang: "Irish",          greeting: "Dia duit ar maidin"
"italian":        lang: "Italian",        greeting: "Buon giorno"
"japanese":       lang: "Japanese",       greeting: "Ohayo gozaimasu"
"kannada":        lang: "Kannada",        greeting: "Shubhodaya"
"kapampangan":    lang: "Kapampangan",    greeting: "Mayap a abak"
"kazakh":         lang: "Kazakh",         greeting: "Kairly Tan"
"khmer":          lang: "Khmer",          greeting: "Arrun Suo Sdey"
"kimeru":         lang: "Kimeru",         greeting: "Muga rukiiri"
"kinyarwanda":    lang: "Kinyarwanda",    greeting: "Muraho"
"konkani":        lang: "Konkani",        greeting: "Dev Tuka Boro Dis Divum"
"korean":         lang: "Korean",         greeting: "Annyunghaseyo"
"kurdish badini": lang: "Kurdish Badini", greeting: "Spede bash"
"kurdish sorani": lang: "Kurdish Sorani", greeting: "Beyani bash"
"lao":            lang: "Lao",            greeting: "Sabaidee"
"latvian":        lang: "Latvian",        greeting: "Labrit"
"lithuanian":     lang: "Lithuanian",     greeting: "Labas rytas"
"lozi":           lang: "Lozi",           greeting: "U zuhile"
"luganda":        lang: "Luganda",        greeting: "Wasuze otyano"
"luo":            lang: "Luo",            greeting: "Oyawore"
"luxembourg":     lang: "Luxembourg",     greeting: "Gudde moien"
"macedonian":     lang: "Macedonian",     greeting: "Dobro utro"
"malayalam":      lang: "Malayalam",      greeting: "Suprabhatham"
"malay":          lang: "Malay",          greeting: "Selamat pagi"
"maltese":        lang: "Maltese",        greeting: "Għodwa it-tajba"
"manx":           lang: "Manx",           greeting: "Moghrey mie"
"maori":          lang: "Maori",          greeting: "Ata marie"
"mapudungun":     lang: "Mapudungun",     greeting: "Mari mari"
"marathi":        lang: "Marathi",        greeting: "Suprabhat"
"mongolian":      lang: "Mongolian",      greeting: "Öglouny mend"
"navajo":         lang: "Navajo",         greeting: "Yá'át'ééh abíní"
"ndebele":        lang: "Ndebele",        greeting: "Livukenjani"
"nepali":         lang: "Nepali",         greeting: "Subha prabhat"
"northern sotho": lang: "Northern Sotho", greeting: "Thobela"
"norwegian":      lang: "Norwegian",      greeting: "God morgen"
"owambo":         lang: "Owambo",         greeting: "Wa lalapo"
"pashto":         lang: "Pashto",         greeting: "Sahar de pa Khair"
"persian":        lang: "Persian",        greeting: "Subbakhair"
"pirate":         lang: "Pirate",         greeting: "Avast, ye scurvy dog"
"polish":         lang: "Polish",         greeting: "Witaj"
"polynesian":     lang: "Polynesian",     greeting: "Ia ora na"
"portuguese":     lang: "Portuguese",     greeting: "Bom dia"
"punjabi":        lang: "Punjabi",        greeting: "Sat Shri Akal"
"rapa nui":       lang: "Rapa Nui",       greeting: "Iorana"
"romanian":       lang: "Romanian",       greeting: "Buna dimineata"
"russian":        lang: "Russian",        greeting: "Dobroye utro"
"samoan":         lang: "Samoan",         greeting: "Talofa lava"
"sanskrit":       lang: "Sanskrit",       greeting: "Suprabhataha"
"sardinian":      lang: "Sardinian",      greeting: "Bona dia"
"serbian":        lang: "Serbian",        greeting: "Dobro jutro"
"shona":          lang: "Shona",          greeting: "Mangwanani"
"sinhalese":      lang: "Sinhalese",      greeting: "Suba Udesanak Wewa"
"slovak":         lang: "Slovak",         greeting: "Dobré ráno"
"slovenian":      lang: "Slovenian",      greeting: "Dobro jutro"
"somalian":       lang: "Somalian",       greeting: "Subax wanaagsan"
"southern sotho": lang: "Southern Sotho", greeting: "Dumela"
"spanish":        lang: "Spanish",        greeting: "Buenos dias"
"swahili":        lang: "Swahili",        greeting: "Habari za asubuhi"
"swazi":          lang: "Swazi",          greeting: "Sawubona"
"swedish":        lang: "Swedish",        greeting: "God morgon"
"tagalog":        lang: "Tagalog",        greeting: "Magandang umaga"
"taiwanese":      lang: "Taiwanese",      greeting: "Gau cha"
"tamil":          lang: "Tamil",          greeting: "Kaalai Vannakkam"
"telugu":         lang: "Telugu",         greeting: "Subhodayamu"
"tetum":          lang: "Tetum",          greeting: "Dader diak"
"thai":           lang: "Thai",           greeting: "Aroon-Sawass"
"tibetan":        lang: "Tibetan",        greeting: "Nyado delek"
"tonga":          lang: "Tonga",          greeting: "Mwabuka buti"
"tswana":         lang: "Tswana",         greeting: "Dumela"
"twi":            lang: "Twi",            greeting: "Me ma wo maakye"
"turkish":        lang: "Turkish",        greeting: "Günaydin"
"turkmen":        lang: "Turkmen",        greeting: "Ertiringiz haiyirli bolsun"
"ukrainian":      lang: "Ukrainian",      greeting: "Dobri ranok"
"urdu":           lang: "Urdu",           greeting: "Subha Ba-khair"
"uzbek":          lang: "Uzbek",          greeting: "Khairli kun"
"vietnamese":     lang: "Vietnamese",     greeting: "Xin chao"
"welsh":          lang: "Welsh",          greeting: "Bore da"
"xhosa":          lang: "Xhosa",          greeting: "Bhota"
"xitsonga":       lang: "Xitsonga",       greeting: "Avuxeni"
"yoruba":         lang: "Yoruba",         greeting: "E karo"
"zulu":           lang: "Zulu",           greeting: "Sawubona"
"!kung san":      lang: "!Kung san",      greeting: "Tuwa"
"australian":     lang: "Australian",     greeting: "G'day"
"klingon":        lang: "Klingon",        greeting: "nuqneH"
"tlhingan hol":   lang: "tlhIngan Hol",   greeting: "nuqneH"
"vulcan":         lang: "Vulcan",         greeting: "Dif-tor heh smusma"
"romulan":        lang: "Romulan",        greeting: "Brhon mnekha"
"ferengi":        lang: "Ferengi",        greeting: "Welcome to our home. Please place your thumbprint on the legal waivers and deposit your admission fee in the slot by the door. Remember, my house is my house,"



class GreetingsRepository
    GREETINGS = greetings

    find: (name) ->
        GREETINGS[name.toLowerCase()]

    findOrRandom: (robot, name) ->
        name? && @find(name) || @random(robot)

    greeting: (name) ->
        @find(name)?.greeting

    all: ->
        GREETINGS

    names: ->
        for k,v of GREETINGS
            v.lang

    keys: ->
        Object.keys(GREETINGS)

    random: (robot) ->
        GREETINGS[robot.random @keys()]


module.exports = GreetingsRepository
